#!/usr/bin/env python3

import sys

import wikiparse

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Please pass in two arguments: [article.txt] [questions.txt]")
        exit(0)

    wikiparse.answer(sys.argv[1], sys.argv[2])
